### PR TITLE
clean direct buffer

### PR DESCRIPTION
**Pull request by atmoshaman**
clean direct buffer @stevehu

### CODE REVIEW

**Comment by stevehu** [comment]
@atmoshaman Thanks a lot for the PR. I am trying to search other places direct buffers are used.

**Comment by stevehu** [comment]
I was trying to figure out if any other places need to be updated but never got a chance. Merged it first to resolve the current issue. Thanks a lot for your help.

**Comment by stevehu** [comment]
I have to roll back the change as the request to the service will freeze forever. Do you know the root cause?

**Comment by atmoshaman** [comment]
Sorry, The original code used IoCallback to deallocate DirectByteBuffer, The buffer could be freed while Undertow was still sending data, This premature deallocation caused the request to freeze.

**Comment by stevehu** [comment]
OK. I understand now. Let's closely monitor the current code for while. Thanks.

**Comment by atmoshaman** [comment]
> OK. I understand now. Let's closely monitor the current code for while. Thanks.

#155 please review.

**Pull request merged**
